#include <LiquidCrystal.h>

// -------- PINOS DO LCD --------
LiquidCrystal lcd(12, 11, 5, 4, 3, 2);

// -------- PINOS DOS COMPONENTES--------
const int sensorFumaca = A0;   
const int sensorTemp = A1;     
const int ledVerde = 8;        
const int ledVermelho = 9;     
const int buzzer = 13;         

void setup()
{
  Serial.begin(9600);
  lcd.begin(16, 2);
  
  pinMode(ledVerde, OUTPUT);
  pinMode(ledVermelho, OUTPUT);
  pinMode(buzzer, OUTPUT);
  
  // Tela de Inicialização
  lcd.clear();
  lcd.setCursor(0, 0);
  lcd.print("      GS       ");
  lcd.setCursor(0, 1);
  lcd.print("   OrbitEye   ");
  delay(2000);
  lcd.clear();
}

void loop()
{
  // LEITURA DO SENSOR DE FUMAÇA
  int valorFumaca = analogRead(sensorFumaca);
  
  // LEITURA E CÁLCULO DA TEMPERATURA (TMP36)
  int leituraLeve = analogRead(sensorTemp);
  float voltagem = leituraLeve * (5.0 / 1023.0); 
  float temperaturaC = (voltagem - 0.5) * 100.0; 
  
  // Exibe os dados no LCD
  lcd.setCursor(0, 0);
  lcd.print("F:");
  lcd.print(valorFumaca);
  lcd.print(" ");
  lcd.print("T:");
  lcd.print(temperaturaC, 1); 
  lcd.print("C   ");

  // Mostra no Monitor Serial para depuração
  Serial.print("Fumaca: ");
  Serial.print(valorFumaca);
  Serial.print(" | Temp: ");
  Serial.print(temperaturaC);
  Serial.println(" C");

  // ====================================================
  // CONDICAO DE ALERTA (Fumaça > 700 OU Temp > 60°C)
  // ====================================================
  if (valorFumaca > 300 || temperaturaC > 60.0)
  {
    digitalWrite(ledVerde, LOW);       
    digitalWrite(ledVermelho, HIGH);   
    tone(buzzer, 1000);                
    
    lcd.setCursor(0, 1);
    lcd.print("ALERTA: INCENDIO");
  }
  // ====================================================
  // AMBIENTE SEGURO 
  // ====================================================
  else
  {
    digitalWrite(ledVerde, HIGH);      
    digitalWrite(ledVermelho, LOW);    
    noTone(buzzer);                    
    
    lcd.setCursor(0, 1);
    lcd.print("Ambiente Seguro ");
  }
  
  delay(1000); 
}
